# Generated by Django 5.0.2 on 2025-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$T8kzvOW43OwZyv7K3QuLWp$KIYIbiwbnqSdNxr5K7slhaTswOhxQw+xt9yQyUJJYgg=', max_length=128),
        ),
    ]
