# Generated by Django 5.0.2 on 2025-06-17 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_registration_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$psgs3YxXn9ipGsrqISmTxa$Y3xv0CqHtbX3vSJquoexQye3OxmhcX44TFggUeuvP8M=', max_length=128),
        ),
        migrations.CreateModel(
            name='TradingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOREX', 'Forex'), ('COMEX', 'Comex'), ('STOCKS', 'Stocks'), ('CRYPTO', 'Crypto')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'symbol'],
                'unique_together': {('user', 'category', 'symbol')},
            },
        ),
    ]
