# Generated by Django 5.0.2 on 2025-06-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_registration_password_tradingconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$uroEXGn4eXt2NugjibJExG$b7wNISMfax5OW1PmfmgdHPg966fGnSX7LrXXhvE+YhQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='tradingconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_configs', to='first_app.registration'),
        ),
    ]
