# Generated by Django 5.2.3 on 2025-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_franchise_alter_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$lDQjh40vuHqu6YD6IuWMqa$HM4hKGRlpWKnf2FZcoicBQ5UJQsDoScTVUuhXniNEAY=', max_length=128),
        ),
    ]
