# Generated by Django 5.2.3 on 2025-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_registration_is_admin_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$PFYuNpJikGaE9ZaiH3hGN1$p0+7BJ2DWmTugYMpRfRTQhg3m/1eBn2M0Er/hsrd0W8=', max_length=128),
        ),
    ]
